require: rubocop-rspec

inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

AllCops:
  TargetRubyVersion: 2.6

Rails:
  Enabled: true

Rails/SaveBang:
  Enabled: true

Layout/ClassStructure:
  Enabled: true

Style/ImplicitRuntimeError:
  Enabled: true

Style/StringMethods:
  Enabled: true

