require:
  - rubocop-rspec
  - rubocop-i18n

inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

AllCops:
  TargetRubyVersion: 2.6

GetText:
  Enabled: false

Rails:
  Enabled: true

Rails/SaveBang:
  Enabled: true

RailsI18n:
  Enabled: true
  Exclude:
    - spec/*
    - app/models/concerns/*.rb # TODO

Layout/ClassStructure:
  Enabled: true

Performance/CaseWhenSplat:
  Enabled: true

Style/ImplicitRuntimeError:
  Enabled: true

Style/StringMethods:
  Enabled: true

